CREATE TABLE produtos (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255) NOT NULL,
  PRECO DECIMAL(10,2),
  QUANTIDADE INT NOT NULL DEFAULT 0
);

CREATE TABLE historico_estoque (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PRODUTO_ID INT,
  QUANTIDADE_ANTIGA INT,
  QUANTIDADE_NOVA INT,
  DATA_ALTERACAO DATETIME
);

DELIMITER $$

CREATE TRIGGER registrar_alteracao_estoque
AFTER UPDATE ON produtos
FOR EACH ROW
BEGIN
  IF OLD.QUANTIDADE <> NEW.QUANTIDADE THEN
    INSERT INTO historico_estoque
      (PRODUTO_ID, QUANTIDADE_ANTIGA, QUANTIDADE_NOVA, DATA_ALTERACAO)
    VALUES
      (OLD.ID, OLD.QUANTIDADE, NEW.QUANTIDADE, NOW());
  END IF;
END$$

DELIMITER ;

INSERT INTO produtos (NOME, PRECO, QUANTIDADE) VALUES ('CANETA AZUL', 100.00, 50);
INSERT INTO produtos (NOME, PRECO, QUANTIDADE) VALUES ('BONECO DO MANUEL GOMES', 800.00, 10);

UPDATE produtos SET QUANTIDADE = 30 WHERE ID = 1;
UPDATE produtos SET QUANTIDADE = 20 WHERE ID = 1;

SELECT * FROM historico_estoque;
