CREATE TABLE produtos(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL,
  PRECO DECIMAL(10,2),
  QUANTIDADE INT NOT NULL
);


CREATE TABLE quantidade_estoque(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  FK_PRODUTO INT,
  OLD_QUANTIDADE DECIMAL(10,2),
  NEW_QUANTIDADE DECIMAL(10,2),
  DATA_ALTERACAO DATETIME DEFAULT CURRENT_TIMESTAMP
);



DELIMITER $$

CREATE TRIGGER registrar_alteracao_estoque
 AFTER UPDATE ON produtos
  FOR EACH ROW 
  BEGIN 
    IF OLD.QUANTIDADE <> NEW.QUANTIDADE THEN
    INSERT INTO quantidade_estoque (FK_PRODUTO, OLD_QUANTIDADE, NEW_QUANTIDADE, DATA_ALTERACAO)
    VALUES (OLD.ID, OLD.QUANTIDADE, NEW.QUANTIDADE, NOW());
    END IF ;
  END $$

    DELIMITER ;


    INSERT INTO produtos (NOME, PRECO, QUANTIDADE) VALUES ("CANETA AZUL", 10.00, 6);
    INSERT INTO produtos (NOME, PRECO, QUANTIDADE) VALUES ("CANETA PRETA", 10.00, 7);


    UPDATE produtos SET QUANTIDADE = 10 WHERE NOME = "CANETA AZUL";
    UPDATE produtos SET QUANTIDADE = 20 WHERE NOME = "CANETA AZUL";

    SELECT*FROM quantidade_estoque;

    
